files:
  - 
    source: /res/values/strings.xml
    translation: '/res/values-%two_letters_code%/string.xml'
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
    translate_attributes: "0"
